- src/components/ChartContainer/index.js
- src/components/DataProvider/index.js
- src/components/LineChart/index.js
- stories/index.js
By using the following configuration options on the <DataProvider>, the
y axes will not be rendered (the series still will be).
config: {
yAxis {
display: 'NONE',
}
}
Supported values are 'NONE' and 'ALL'. Any other values will behave as
if 'ALL' was specified.
> Allow the Y axes to be removed

- src/components/Axis.js
- src/components/LineChart/index.js
- stories/index.js
Add a new flag (zoomable) to the config object which allows for the
chart to be rendered without zooming. Disabling zooming for the chart
also disables zooming of the axes.
> Allow disabling of chart zooming

- src/components/Axis.js
- src/components/LineChart/index.js
- stories/index.js
When disabling the zooming feature, disable it at the d3 level so that
it doesn't interfere with scrolling.
> Correclty handle disable zooming

- src/components/LineChart/index.js
If the caller has asked for onMouseOut to be called (by weay of
specifiying a callback), then call it when onMouseOut occurs.
> If onMouseOut was passed to LineChart, call it

- src/components/DataProvider/index.js
- src/components/LineChart/index.js
- stories/index.js
Use an object for the strokeWidth parameter, rather than an array.
> Use key, not index, for strokeWidth

- src/components/AxisCollection/YAxis.js
- src/components/AxisCollection/index.js
- src/components/ChartContainer/index.js
- src/components/ContextChart/index.js
- src/components/DataProvider/index.js
- src/components/LineChart/index.js
- src/data/Series.js
- src/data/index.js
- stories/index.js
As data enters the DataProvider, convert it into an instance of a Series
object. This will contain all of the metadata as well as the functions
that callers will use down the line, like scale calculations.
This also allows the callers to have the metadata live directly with the
series object passed in from the loader, instead of as a series of
disconnected metadata objects (eg: hiddenSeries, colors, strokeWidths).
Backwards compatibility is maintained by mixing the metadata arrays in
the DataProvider, with the series object's metadata taking precedence.
Finally, create an AxisCollection object and extract a dedicaetd YAxis
object. These maintain single-responsibility behavior, where they are
only responsible for rendering their level of data. This gives us much
more manageable code in …
> Create an encapsulated Series object

- src/components/ContextChart/index.js
- src/data/Series.js
When drawing the lines on the ContextChart, do not use the scale()
method on the Series object -- this will lead to dynamic scaling in the
ContextChart, which is not what we want. Instead, extract out a
staticScale() method to ignore the current scaling.
> Do not scale the ContextChart

- src/data/Series.js
As part of the Series migration, this copy-and-paste error got missed.
Pull the correct object to for calculating data.
> Use "this.data" instead of "data"

- .eslintignore
- .eslintrc.json
- package.json
- yarn.lock
Added cognite-react-scripts in order to have eslint and prettier capabilities in the project. Also added `yarn build:watch` script which basically listens for the source code changes and runs `yarn build`, which is pretty handy when repository is used as a link.
> Add eslint and prettier support

- src/components/Line/index.js
- src/components/LineChart/index.js
- stories/index.js
If y0Accessor and y1Accessor are specified with a series, draw an area
surrounding the line. This allows for uncertainty to be drawn if
desired.
> Add support for min/max area

- src/components/Brush/index.js
- src/components/ContextChart/index.js
- src/components/Scaler/index.js
- src/index.js
- stories/index.js
D3’s brush actually updates the DOM - which means that draws to the DOM happens without react knowing about it, hence not being able to be clever about the virtual dom diffing (I think). D3s zoom however only attaches an event listener to a given object and leaves the rest up to the user (great). Also, the zoom events are a lot more complicated to replicate as it handles all kinds of touch events. D3s brush is also a lot more complicated than necessary as it’s built to handle xy zoom which we’re not using.
Debug this with touch events, if that will ever become a use case. Currently — Operation Support is not using the context chart afaik, so there’s no rush there.
> Implementation of custom brush

- src/components/AxisCollection/YAxis.js
Give a notion that the yAxis can in fact be scrolled/panned by adding `cursor: move` when zoomable and `inherit` when non-zoomable.
> Yaxis cursor

- .prettierignore
- package.json
- src/components/AxisCollection/YAxis.js
- src/components/AxisCollection/index.js
- src/components/DataProvider/index.js
- src/components/InteractionLayer/index.js
- src/components/LineChart/index.js
- src/components/XAxis.js
- src/utils/proptypes.js
- stories/index.js
- yarn.lock
If y0Accessor and y1Accessor are specified, use those to calculate the
domain for the chart.
This has disastrous consequences if the user of griff also uses
styled-components, and with a different version (virtually guaranteed).
This change also involved an attempt to move to CSS Grid to
automatically determine the components sizes, but without relying on
sizeMe. However, this was aborted for the time being, with some small
sizing remnants hiding in the code. One example is the new contextChart
config, which looks like this:
```
contextChart: PropTypes.shape({
// Whether to show the context chart at all.
visible: PropTypes.bool,
// How high (in pixels) the context chart should be. Note that an
// extra 50 pixels will be added for its X axis.
height: PropTypes.number,
// How high (in …
```
> Clean up bugs found in the 0.2.0 migration

- src/components/Annotation/index.js
- src/components/AxisCollection/CollapsedAxis.js
- src/components/AxisCollection/index.js
- src/components/ContextChart/index.js
- src/components/InteractionLayer/index.js
- src/components/LineChart/AxisDisplayMode.js
- src/components/LineChart/index.js
- src/utils/proptypes.js
- stories/index.js
Add support for several y-axis display modes:
ALL: Show all of the axes.
NONE: Don't show any of the axes.
COLLAPSED: Hide the real axes and instead render a single generic axis
without values or color.
This also adds event listeners to AxisCollection, as specified via
onAxisMouseEnter / onAxisMouseExit properties on LineChart.
> Add AxisDisplayMode functionality

- src/components/DataProvider/index.js
- src/components/Scaler/index.js
- stories/index.js
There was a clash implementing live loading as it introduced another handle whenever the baseDomain changed.
This PR makes `DataProvider` pass down both the `baseDomain` (may be internally updated) and `externalBaseDomain` which is its original prop. Then, the `Scaler` handles a change in `baseDomain` by keeping the subdomain (live loading) and the change in `externalBaseDomain` by resetting its entire state.
> Fixing dynamic base domains

- src/components/XAxis.js
In opsup we have a problem of overlapping xAxis labels for smaller devices. This is basically because griff relies on d3 [`axis.ticks()`](https://github.com/d3/d3-3.x-api-reference/blob/master/SVG-Axes.md#ticks) which default number is 10 no mater width the chart has. It seems there is no any proper solution over there, so I came up with idea of just passing a number of ticks depending on the width. Better ideas of course are welcome.
> Ticks amount depends on the width

- src/components/Line/index.js
- src/components/LineCollection/index.js
- stories/index.js
For each instance of LineChart, name the clipPath a unique identifier so
that multiple LineChart instances on a page do not collide
> Use a unique clipPath for each LineChart

- src/components/InteractionLayer/index.js
`this.props.ruler` will always be truthy; we need to check whether it is
visible or not.
> Don't check for ruler; check for ruler.visible

- src/components/InteractionLayer/index.js
If onAreaDefined is not specified, then don't try to create areas.
> Gate area-creation with onAreaDefined

- src/components/Brush/index.js
The visible area should be clear, and the nonvisible area should be
dimmed.
> Invert the context chart shading

- src/components/Brush/index.js
Due to floating-point math, we can wind up with a negative width,
which results in a warning in the console.
The rect should be zero-width anyway, so bound them to 0.t
> Don't allow `<rect>` to be negative

- src/utils/proptypes.js
`PropTypes.shape` cannot take in a class, so define the shape we
actually need instead.
> Fix "checker is not a function" warning

- src/components/InteractionLayer/index.js
To reproduce navigate to 'Live loading and ruler' story. By clicking or touching the chart, ruler should stick with the selected point during live loading. By dragging the chart ruler should stay on the same x position.
> Ruler touch behavior should differ from hover

- src/utils/proptypes.js
The area ID is opaque to griff -- accept either a string or a number.
> Allow either a string or a number for Area ID

- src/components/InteractionLayer/index.js
- src/utils/proptypes.js
- stories/index.js
If for some reason we get a mouseup event before we get a mousedown
event, the `area` variable can be null. In this case, we should simply
silently fail instead of crashing.
> Check for `area` existence before using it

- src/components/Area/index.js
- src/utils/proptypes.js
Consolidate all of the `id` props into a single proptype definition --
which can be a number or a string.
Additionally, don't require `Area` to have a start and end property
since this won't happen when the area first pops into existence.
> Extract an idPropType

- package.json
- yarn.lock
This allegedly fixes the `onShrink`/`onExpand` error, as described in
ctrlplusb/react-sizeme#135
> Upgrade react-sizeme to 2.4.4

- src/components/LineChart/index.js
- stories/index.js
Leverage `react-sizeme` to make LineChart always be the size of its
container, instead of needing to specify dimensions.
> Have LineChart be the size of its container

- README.md
- package.json
- scripts/publish-release.js
Document how the branches play together, what the versions will be, and
how to make changes to griff. This also adds a script (run with `yarn
release`) to determine the new version number, publish a release, and
push the tag to GitHub.
This is a cherry-pick of 4cfe5bf and sets the version to `0.3.0-0` for
pre-release builds.
> Document the branch layout & versioning system (#116)

- src/components/Line/index.js
- stories/LineChart.stories.js
If raw points are going to be drawn, then don't also draw the min/max
uncertainty area.
> Don't render area if points are drawn

- src/components/GridLines/index.js
- src/components/LineChart/index.js
- src/utils/proptypes.js
- stories/GridLines.stories.js
Expose a `grid` property on the LineChart which controls the grid line
specification. This object is documented in `proptypes.js`, but here's a
summary:
The `y` property of the grid specification controls how horizontal
lines behave (they're distributed along the Y values). These can either
be rendered statically or linked to one or more series. If there are
links, then the grid lines will be transformed just like the y-axis tick
marks as the data is scaled.
The `x` property of the grid specification controls how vertical lines
behave (they're distributed along the X values). Similarly, these can
either be rendered statically or linked to the time value. There is no
series linkage necessary for this, because the x-axis is independent of
the series being plotted.
Fixes #113
> Add support for grid lines

- .storybook/config.js
- src/components/AxisCollection/CollapsedAxis.js
- src/components/AxisCollection/YAxis.js
- src/components/AxisCollection/index.js
- src/components/LineChart/AxisDisplayMode.js
- src/components/LineChart/AxisPlacement.js
- src/components/LineChart/Layout.js
- src/components/LineChart/index.js
- src/index.js
- src/utils/proptypes.js
- stories/YAxisPlacements.stories.js
Add a new `yAxisPlacement` property to both LineChart and series. This
value is one of the defined `AxisPlacement` constants, and it controls
where the respective axes/axis live/s.
It has the following behaviors:
- UNSPECIFIED
- Same as not using the property, and the default value (RIGHT) is used.
-  RIGHT
- Default behavior -- the y-axes are rendered to the right of the line chart.
-  LEFT
- Axes are rendered to the left of the line chart; series are mirrored so that the proximity to the chart is preserved.
-  BOTH
- Axes are rendered on both sides of the chart. These are kept in sync with each other.
If the series objects specify this option, then they will be placed as
specified, overriding the chart's value if necessary.
Fixes #89
> Support configurable axis placements

- package.json
Publishing without building just publishes bad packages. Oops.
> Do a build before releasing

- src/components/DataProvider/index.js
- src/index.js
- src/utils/proptypes.js
Instead of using a class with only static properties, export an object
from `proptypes.js`. No only is this more efficient, but it would
otherwise crash. For example, `GriffPropTypes.collections` was referring
to `GriffPropTypes.collection`, but `GriffPropType` was in the process
of being defined. By moving to a collection of consts, this problem is
avoided.
> Don't use a class for static constant holders

- Jenkinsfile
- package.json
- scripts/publish-release.js
- scripts/publish-release.sh
Jenkins wasn't logging in with its GitHub credentials, so the tags could
not be pushed properly. Fix this.
> Fix publishing of tags

- src/components/Line/index.js
Expose all of the properties necessary so that client applications can
choose their own styles for the min/max area shade, if desired.
> Allow min/max area to be styled with CSS

- src/components/AxisCollection/YAxis.js
- src/components/ContextChart/index.js
- src/components/DataProvider/index.js
- src/components/LineCollection/index.js
- src/components/Scaler/index.js
- src/utils/proptypes.js
- stories/LineChart.stories.js
Support the y axis having a subdomain property, much like the x axis
does. In the interest of maintaining backwards compatibility, the
property was not renamed, but the equivalence is:
baseDomain => yDomain
subDomain  => ySubDomain
This can be specified on a series, collection, or on the `<DataProvider>`
element. The ySubDomain property is not respected on the context chart,
but otherwise replaces the yDomain property everywhere else.
> Add a notion of ySubDomain

- scripts/publish-release.js
- scripts/publish-release.sh
I think `yarn publish` won't even do the commit if it doesn't know who it is (duh). Gotta init git first -- and in the same subshell as the commit. Hence, all one script.
> Another try at pushing GitHub tags

- src/components/Line/index.js
- src/components/LineChart/index.js
- src/components/LineCollection/index.js
- stories/LineChart.stories.js
Much like the calling application can control the stroke width, they can
also control the width of the points being rendered. This is done with a
new pointWidth property, which can be set on either the LineChart or a
series object.
> Allow the point width to be controlled

- src/components/AxisCollection/CollapsedAxis.js
- src/components/AxisCollection/YAxis.js
- src/components/AxisCollection/index.js
- src/components/DataProvider/index.js
- stories/YAxisModes.stories.js
Correctly handle collections being collapsed, as well as having their
component parts specify that they'd like to be collapsed, without
falling apart.
This is done by ignoring the yAxisDisplayMode on the component series if
it is placed in a collection.
This also contains a nontrivial performance boost with respect to
collections by using more efficient array methods to require fewer
iterations through the collections.
> Allow collections to be collapsed

- src/components/AxisCollection/YAxis.js
YAxis should not be given default series or collections, as that can
only be misleading later on. Instead, they should be null, and the
correct behavior will be explicit during the execution.
> Don't pass in default series & collections

- src/components/InteractionLayer/index.js
Areas which specify both series IDs and `yval` for start and end should
be scaled with the associated series. This is a regression, introduced
with 36361e40aae.
> Make attached areas follow the ySubDomain

- stories/loaders.js
The randomData API changed, and the liveLoader's use of it was missed.
> Fix the liveLoader's use of randomData

- stories/loaders.js
The randomData loader went through a refactoring and the monoLoader was
missed as part of this cleanup.
> Fix the single-value story

- src/components/AxisCollection/YAxis.js
- src/components/AxisCollection/index.js
- src/components/ContextChart/index.js
- src/components/LineChart/index.js
- src/components/Scatterplot/index.js
- src/components/UnifiedAxis/CombinedYAxis.js
- src/components/UnifiedAxis/index.js
- src/components/XAxis.js
- stories/LineChart.stories.js
- stories/Scatterplot.stories.js
Add properties to allow for custom-rendering the tick values on both the
x and y axes. These are specified by the `xAxisFormatter` and
`yAxisFormatter` props on the `LineChart` and `Scatterplot` components.
> Support custom tick formatting

- README.md
- src/components/DataProvider/index.js
`DataProvider` should fetch new data when its `pointsPerSeries` prop is updated so that it can be more responsive (e.g. to window resizing).
> fetch data in DataProvider on pointsPerSeries prop update

- scripts/publish-release.js
When publishing from prerelease to non-prerelease, the loss of a
prerelease version needs to be detected so that the patch version can be
correctly bumped.
> Handle publishing over top of prereleases

- src/components/LineChart/index.js
These props should be set already, but the props aren't populated for
the initial render, so don't require the props to be set.
> Fix PropType warnings

- src/components/LineChart/index.js
These props should be set already, but the props aren't populated for
the initial render, so don't require the props to be set.
> Fix PropType warnings (#167)

- src/components/InteractionLayer/index.js
By mistake instead of ySubDomain we passed yDomain leading to a wrong yAxis placement while yAxis has been zoomed
> Cherry pick ruler fix

- src/components/DataProvider/index.js
- src/components/Scaler/index.js
- src/index.js
- stories/LineChart.stories.js
- tests/index-test.js
- add an `onBaseDomainChanged` prop to `DataProvider`
- allow subDomain to be > baseDomain when checking if we are looking at the front of the window
- maintain initial subDomain length in `getSubdomain`
> add onBaseDomainChanged to DataProvider

- scripts/publish-release.js
When publishing the prerelease, if it's a named prerelease, the returned
object will be `[ 'name', 2 ]` -- we need to extract the correct value.
> Correctly bump the prerelease when bumping

- src/components/DataProvider/index.js
When the xDomain prop is not specified, don't default to [0,0] as this
will lead to incorrect values when calculating the extent of the data.
> Use a correct default xDomain

- stories/Scatterplot.stories.js
In order to have series share a yDomain when they're in a scatterplot,
they all need to be in the same collection. Demonstrate this by adding
stories for this functionality.
> Add stories for collected scatter series

- src/components/DataProvider/index.js
- tests/index-test.js
this is done to ensure that `xSubDomain` is limited at all times instead of only within `onSubDomainChanged`
> call limitXSubDomain inside getSubDomain

- src/components/DataProvider/index.js
- stories/InteractionLayer.stories.js
When an interval is set, the old one (if there is one) should be cleared
first. This won't fix all cases of updating while the component isn't
mounted, but if the variable is overwritten, then there's no way to kill
the zombie.
> Clear intervals before setting new ones

- src/components/LineChart/index.js
Rather than running filter multiple times on an array, run a single
reduce call.
> Use reduce instead of chained filters

- src/components/DataProvider/index.js
- src/components/Points/index.js
- src/utils/proptypes.js
- stories/Scatterplot.stories.js
Introduce uncertainty to the scatterplots by using the same min/max
shaded area. The resulting polygon is defined by the uncertainty
accessors: x0Accessor, x1Accessor, y0Accessor, y1Accessor.
> Bring min/max to the scatterplots

- src/components/DataProvider/index.js
- having `startUpdateInterval` after the `await` inside `componentDidMount` means it is possible for `clearInterval` within `componentWillUnmount` to attempt to clear the interval before it is set
- since we now call `clearInterval` at the start of `startUpdateInterval`, there is no need to call it before every call of `startUpdateInterval`
> clean up clearInterval

- src/components/ZoomRect/index.js
If the user zooms in very quickly (deltaY <= -1), then the newSubDomain
can become inverted -- the end will be before the start. If this
happens, flip them back around.
> Prevent inverted subdomains

- src/components/InteractionLayer/index.js
When there are new props for InteractionLayer, we need to update when:
1. The mouse moves (`mousemove` event)
2. There was no d3 event (live-loading)
All other reasons need to be ignored (eg, `touchmove` events)
> Correctly handle the update events for non-touchmove

- src/components/Scaler/index.js
- src/utils/Axes.js
If the series are updated, it's possible to crash because the subdomain
and domain maps in Scaler have not yet been updated. Example logical
flow:
1. Scaler initialized with series 1.
2. Scaler's state updated with:
domainsByItemId: { [1]: { .. } },
subDomainsByItemId: { [1]: { .. } },
3. Series 2 added to DataProvider
4. Scaler notices the new series and updates the state:
domainsByItemId: { [1]: { .. }, [2]: { .. } },
subDomainsByItemId: { [1]: { .. }, [2]: { .. } },
When this happens, no other scaling happens in componentDidUpdate
because everthing was reinitialized when there are new series added.
As an additional safety measure, Axes will not crash if an invalid
series is given. Instead, a domain (or subdomain) of `[0, 0]` will be
returned.
> Handle missing series in the subdomains

- src/components/DataProvider/index.js
- src/components/Scaler/index.js
Introduce a placeholder domain (owned by Scaler) which will allow for
children to assume a domain exists and is valid, but the Scaler can know
whether or not there is a valid domain or not.
This allows Scaler to use the computed domains and subdomains when
necessary, and use the specified ones when not.
> Formalize the notion of a placeholder domain

- src/components/InteractionLayer/index.js
This check prevents the `onMouseMove` api from providing data if the ruler is hidden/doesn't exist - breaking opints cursor overview.
Not sure if this code was added to solve some kind of other bug though
> Removed the check to see if a ruler exists

- demo/src/index.js
- src/components/InteractionLayer/index.js
- src/components/ZoomRect/index.js
- The ruler should stick to the point it was previously set to when:
- Live loading (i.e. the subDomain changes internally, not due to an action done by the user)
- Zooming and panning on desktop
- The ruler should not stick to the point it was previously set to, but instead should be aligned with the point closest to the x-position it was previously set to when:
- Zooming or panning on mobile
Panning on mobile was broken because `this.firstTouch` in `ZoomRect` was `undefined` it had not previously been set in `onMouseMove` (i.e. if the chart had not yet been hovered over or click on). This was implicitly fixed by the fact that we don't actually need to use `firstTouch` because of how the ruler positioning works in `InteractionLayer`
> Fix mobile panning and ruler behaviour

- src/components/DataProvider/index.js
- src/components/Scaler/index.js
`Scaler` was setting its `timeSubDomain` state before it being limited in `DataProvider`, causing the `timeSubDomain` to jump around (and hence the ruler to jump around) when attempting to pan the chart passed the limit imposed within `limitTimeSubDomain`
> limit timeSubDomain in Scaler

- src/components/DataProvider/index.js
- src/components/Line/index.js
- src/components/LineCollection/index.js
- src/components/PointCollection/index.js
- src/components/Scatterplot/index.js
- src/utils/Axes.js
- src/utils/proptypes.js
- stories/Scatterplot.stories.js
Through the use of a new `drawLines` prop, allow lines to be rendered on
scatterplots. This is shared between line charts and scatterplots, and
has different defaults -- on line charts, it will default to true, but
it will default to false on scatterplots.
> Add lines on scatterplots

- src/components/InteractionLayer/index.js
- src/components/LineChart/index.js
a few fixes here:
1. don't add a `rulerPoint` if there is no data for that series
1. don't attempt to add a `rulerPoint` if there is no entry in `subDomainsByItemId` for the series. (This can happen when a new series is added but an entry for it has not yet been added to `subDomainsByItemId`)
1. update the ruler position on width change and `subDomainsByItemId` change
1.  don't render `InteractionLayer` if its width will be < 0 (this occurs when sizeMe returns a width of 0 for `LineChart`. this is done because otherwise, the calculated xposition for the ruler will be < 0, causing it to be cleared.
> better support ruler positioning for multiple series

- src/components/ContextChart/index.js
- src/components/DataProvider/index.js
- src/components/LineCollection/index.js
- src/components/Scaler/index.js
- src/context/Data.js
- stories/LineChart.stories.js
Make x & y domains behave like time: if there is a domain specified,
then the subdomain cannot go beyond those bounds. If neither are
specified, then the subdomain will default to the extent of the data
(with an open-ended domain).
This also removes the notion of a contextSeries. Instead, have the
context chart (if present) simply transform the series to look how it
wants them to look (static domains, drawPoints=false, etc).
This change also introduces an unconsistency: LineCollection takes in a
yScalerFactory with a different signature than xScalerFactory. This will
be cleaned up in a fast-follow PR (to move xScalerFactory to the same
signature as the new yScalerFactory). This refactor was omitted from
this PR to keep it manageable.
> Rework domains & subdomains for x & y axes

- src/components/Line/index.js
The x domain is not necessarily time anymore, so don't make that
assumption when drawing lines. It's possible that this getTime() call
could be removed entirely, but it's unclear what the side-effects of
doing that would be. Instead, be safe and allow for a smoother
migration.
> Allow drawing lines without time

- src/components/PointCollection/index.js
- src/components/Points/index.js
- stories/Scatterplot.stories.js
Apply a filter before rendering the points so that only points relevant
to the time subdomain (visible time range) are rendered. This allows for
similar behavior to the line chart where changing the time subdomain
shows the low-resolution aggregates before the loader renders the
higher-resolution data.
> Only show points that are within the timeSubDomain

- src/components/Line/index.js
I'm a bit far from the current implementation but it seems if `drawPoints` is a function there is no need to hide min/max areas
> Show min/max areas if drawPoints is a function

- src/components/InteractionLayer/index.js
- src/components/Scaler/index.js
- stories/LineChart.stories.js
the overarching problem here was that in `Scaler`'s `componentDidUpdate`, the `subDomainsByItemId` state was being directly mutated due to this shallow copy on line 176:
` const subDomainsByItemId = { ...this.state.subDomainsByItemId };`
This was causing weird behaviour for the ruler in `InteractionLayer`, since it was not picking up when `subDomainsByItemId` was changing. 
The fix to this was:
- not doing a shallow copy of `subDomainsByItemId`
- placing the check for a change in `timeSubDomain` after the check for a change in `timeDomain` in `Scaler`'s `componentDidUpdate` (the new value from `dataContext.timeSubDomain` should be prioritized over a the new value calculated from a new `dataContext.timeDomain`)
- since `subDomainsByItemId` is now being updated properly in `Scaler`, there …
> make ruler work for live loading and sticky subdomain

- src/components/ContextChart/index.js
- src/components/GridLines/index.js
- src/components/InteractionLayer/index.js
- src/components/Line/index.js
- src/components/LineChart/index.js
- src/components/LineCollection/index.js
- src/components/PointCollection/index.js
- src/components/Scaler/index.js
- src/components/Scatterplot/index.js
- src/components/XAxis/index.js
- src/components/ZoomRect/index.js
- src/utils/scale-helpers.js
- stories/XAxis.stories.js
With the introduction of XAxis' tickFormat functions, we no longer need
to have separate time-based and number-based scales. As a result, remove
the time-based ones and standardize on straight linear scales.
> Remove xScalerFactory and createLinearXScale

- src/components/AxisCollection/YAxis.js
- src/components/XAxis/index.js
added helper funcs and configured the y axis to add padding zeros so that the decimal places stay consistent regardless of how much you zoom the axes - ex 0.00
> allow axes tickFormatter to accept second param of full array of values to display

- stories/LineChart.stories.js
It's hard to know the state of all of the domains, so make the buttons a
little bit more explicit about whether they're enabled or not.
> Clarify the y-axis subdomain story

- src/components/Ruler/index.js
- src/components/RulerTooltip/index.js
Allow the calling applications to override the look and feel of these
components by providing CSS class names for the DOM elements.
> Add CSS class names to Ruler's components

- src/components/GridLines/index.js
In order to allow calling applications to provide their own styles, set
class names on the generated grid lines.
Additionally, convert GridLines from an ES6 class to a stateless
function (since the lines don't have any state).
> Give grid lines class names

- src/components/GridLines/index.js
- src/components/LineChart/index.js
- src/components/Scatterplot/index.js
- src/index.js
- src/utils/proptypes.js
- stories/GridLines.stories.js
- stories/Scatterplot.stories.js
Instead of controlling GridLines through props, allow it to be added
directly to the hierarchy as a child of the desired chart (eg, LineChart
or Scatterplot). This allows for a flatter prop structure as well as
beginning the migration of business logic from inside of Griff back into
the client application.
> Export GridLines as a top-level component

- src/components/DataProvider/index.js
So that other components using this can have custom error handling functionality in case the data fails to come back.
Relates to https://github.com/cognitedata/operational-intelligence/issues/1993
> Add error handler callback to DataProvider

- src/components/DataProvider/index.js
Can be useful for debugging to know exactly what params were passed into the loader which caused it to error.
Missed addressing this comment in #250
> Expose params to error handler on DataProvider loading error

- src/components/AxisCollection/YAxis.js
- src/components/XAxis/index.js
tickFormatter should always get a number (or NaN if we're somehow trying
to plot a non-number object).
> Ensure tickFormatter gets a number (or NaN)

- src/components/LineChart/index.js
- stories/LineChart.stories.js
Be like the Scatterplot
Relates to https://github.com/cognitedata/operational-intelligence/issues/2119
> Allow specifying custom # of y-axis ticks when using LineChart

- package.json
- yarn.lock
Also set the peer dependency to ^16.8.0 so that griff-react can start to
use fancy new features like Hooks.
> Upgrade react to latest

- Jenkinsfile
- scripts/publish-release.sh
When a new release is published, post a message to the #griff Slack
channel. Similarly, if the release fails to publish, then post an error
message.
> Post to Slack when releases are published

- scripts/publish-release.sh
The publishing process creates a git commit, so stash the commit summary
before anything happens to the tree.
> Save the git commit before yarn publish runs

- package.json
- yarn.lock
Friends don't leave friends behind (react was bumped in 4304a64c, but
react-dom was forgotten).
> Bump react-dom to 16.8.5

- src/components/LineChart/Layout.js
When a container is set to 100% height, but the container fails to grow because it has no parent to set its height from, the chart would grow infinitely. This _should_ stop that
> Prevent a chart from growing continuously in height

- Jenkinsfile
When building storybook + TypeScript, you seem to need a much larger
heap. Increase the heap to accomodate this need.
> Increase the heap size for storybook builds

- src/components/PointCollection/index.tsx
- src/components/Points/index.tsx
- src/external.d.ts
- src/internal.d.ts
- tsconfig.json
These two come as a pair, so it makes sense to port them at the same
time.
Also move tsc to use `moduleResolution: node` to handle the default
imports/exports.
> Ported Points and PointCollection to TypeScript

- package.json
- src/utils/proptypes.js
- tsconfig.json
Publish the module as ES5 so that legacy systems can still use the
project.
Also resolve some dependency issues.
> Build with ES5

- src/components/Scaler/index.tsx
Remove the @ts-ignore declarations in Scaler/index.tsx by making the
known-to-be-safe assumptions explicit through casting.
> Make TypeScript happier with Scaler

- src/components/Brush/index.tsx
- src/components/XAxis/index.tsx
When taking a known Domain (`[number, number]`) and running a `.map()`
function on it, TypeScript loses all knowledge of the fact that this
array is still a `[number, number]` (because it doesn't have to be).
Address this by explicitly casting these back to Domain afterwards so
that we don't need to disable TypeScript checking on the subsequent
line.
> Explicitly cast domain.map to Domain

- src/components/AxisCollection/YAxis.js
- src/components/AxisCollection/index.js
- src/components/ContextChart/index.js
- src/components/GridLines/index.tsx
- src/components/InteractionLayer/index.js
- src/components/LineChart/index.js
- src/components/LineCollection/index.tsx
- src/components/PointCollection/index.tsx
- src/components/Scaler/index.tsx
- src/components/XAxis/index.tsx
- src/components/ZoomRect/index.js
- src/utils/displayName.ts
- stories/ContextChart.stories.js
When components are exported as a function (such as when using the
Context API), they lose the displayName property. Add this back in so
that external tools (such as storybook's info addon) work better.
> Add displayName to all exported components

- src/components/Brush/index.tsx
I don't know when this changed to give them strokes by default, but it
makes the rendering weird. Set them back to none to remove the visual
clutter.
> Remove strokes from the Brush handles

- src/components/Scatterplot/index.js
For some reason, Scatterplot was rendering its own Scaler. This doesn't
do anything except add unnecessary overhead, so go ahead and remove it.
> Don't nest an extra Scaler for Scatterplot

- src/components/GridLines/index.tsx
This was leftover as a TODO during a previous TypeScript migrationl;
clean it up to be more explicit about what it looks like.
> Clean up an `any` type declaration

- README.md
Removes old reference to demos in griff
> chore: remove outdated docs

- src/components/Scaler/index.tsx
The domain should not be considered changed unless its values have changed. We were previously checking by reference.
This fixes a bug where the domains are recalculated when another series prop (not a domain or subdomain prop) is changed.
> Compare domains by values to detect changes

- CODEOWNERS
`@cognitedata/griff-team` owns the code here, not specific people.
> Specify team ownership, rather than individuals

- src/components/InteractionLayer/index.js
- stories/Collection.stories.js
When calculating ruler points the subdomain of the collection should be used (if available) instead of the subdomain of the individual series. Also added a story to test this functionality.
Once this is merged, bumping this package in insight will fix [OI-1832]
[OI-1832]: https://cognitedata.atlassian.net/browse/OI-1832
> [OI-1832] Fix positioning of ruler points

- src/components/InteractionLayer/index.js
This way keys won't clash if annotations and areas have the same ids.
> fix: Make annotation and area keys more specific

- src/components/InteractionLayer/index.js
- stories/InteractionLayer.stories.js
Updated a story so that it could show this problem on first glance.
I can't wait to have snapshot tests for things like this.
> fix: Falsy values (0) cause bounds to be ignored

- src/components/DataProvider/index.js
If there isn't data in the DataProvider, and there wasn't any returned
by the loader, then we shouldn't crash. Instead, handle this gracefully
by assuming no data.
> Handle when there is no data in the loader

- src/components/InteractionLayer/index.js
If min values fall below 0, they will still get subtracted from the max value, create a negative value, which would be `Math.abs`'d and create bad circumstances.
> Added clamp to min values of areas
