cognitedata/griff-react

src/components/LineChart/index.js, stories/index.js
If the difference between the upper and lower bounds of the calculate domain is 0 ( < 1e-3 ), it means for domain [a,b], a == b. In which case, the domain is represented as
`[a - (a/2), a + (a/2)]`.
=> Always representing a domain [a,b] as y domain where a !== b.

src/components/DataProvider/index.js
We should be comparing this.props.config against prevProps.config, not
against prevProps.
=> Compare the correct configs

src/components/LineChart/index.js
Don't make drawing the crosshairs dependent on having all of the data.
Additionally, push an empty data object into the returned array when
mousing around the chart.
=> Always draw crosshairs

stories/index.js
LineChart / DataProvider are expecting an object, not an array.
=> Fix the warnings on the storybook

src/components/InteractionLayer/index.js, src/components/LineChart/index.js, src/components/Ruler/index.js, src/components/RulerTooltip/index.js, src/utils/proptypes.js, stories/index.js, yarn.lock
This is a child PR of https://github.com/cognitedata/griff-react/pull/47
=> 0.2.0 Ruler functionality

Jenkinsfile, package.json, yarn.lock
Proposal for visual storybook every pr using surge as a static hosting provider.
=> Host PRs on surge, deploy to surge on master.

src/components/Line/index.js, stories/index.js
Make the min/max shaded area handle step series a lot better by using
the same curve as used for step series.
=> Add support for min/max on step series

src/index.js, stories/index.js
This needs to be exported so that clients can use this.
=> Export AxisDisplayMode

src/components/AxisCollection/CollapsedAxis.js, src/components/AxisCollection/YAxis.js
Same fix as for xAxis but for yAxis. Personally I don't like those almost `random` numbers (100 and 50) , better ideas of course are welcome.
=> Calculate ticks of yAxis based on height

src/components/AxisCollection/CollapsedAxis.js, src/components/AxisCollection/index.js
Render the placeholder CollapsedAxis to the outside of the
AxisCollection instead of the inside. It shouldn't be between the real
axes and the chart contents.
=> Move the collapsed axis to the outside

src/components/DataProvider/index.js, src/components/InteractionLayer/index.js, src/components/Scaler/index.js, stories/index.js
Fix https://github.com/cognitedata/griff-react/issues/54
=> Add possibility to pass subDomain to DataProvider

src/components/Area/index.js, src/components/InteractionLayer/index.js, src/components/LineChart/index.js, src/utils/proptypes.js, stories/index.js
Allow the user to define areas, and support adding areas.
=> Support user-defined areas

src/components/AxisCollection/CollapsedAxis.js, src/components/AxisCollection/YAxis.js, src/components/AxisCollection/index.js, src/components/LineChart/index.js, stories/index.js
Instead of triggering axis mouse events on the `<AxisCollection>`, set
them on each axis, and add the series ID to the callback.
Mouse events on the collapsed axis are passed with a series ID of
'collapsed'.
=> Change the axis events to be per-axis

src/components/AxisCollection/CollapsedAxis.js
Change the data-agnostic y axis to three vertical grayscale bars.
=> Use a prettier collapsed y axis

src/components/Scaler/index.js
There was a problem that externally set subDomain could not be zoomed
=> SubDomain update fix second try

src/components/InteractionLayer/index.js
There was the problem that ruler started follow the point only after second update
=> Ruler should following point second try

.storybook/config.js, package.json, stories/InteractionLayer.stories.js, stories/LineChart.stories.js, stories/YAxisModes.stories.js, yarn.lock
Move the withInfo call to the global storybook config so that stories
are rendered with their props and source code inline.
=> Show storybook info inline

src/components/InteractionLayer/index.js, src/components/LineChart/index.js, stories/InteractionLayer.stories.js, yarn.lock
Allow the client application to receive a callback when a double-click
happens on the chart.
=> Add support for onDoubleClick

Jenkinsfile
In order to get master tested, auto-publish pre-release versions cut
from the master branch as they get merged.
=> Auto-publish builds from master

src/components/AxisCollection/CollapsedAxis.js, src/components/AxisCollection/YAxis.js, src/components/AxisCollection/index.js, src/components/ContextChart/index.js, src/components/LineChart/AxisPlacement.js, src/components/LineChart/Layout.js, src/components/LineChart/index.js, src/components/LineCollection/index.js, src/components/XAxis.js, src/utils/proptypes.js, stories/LineChart.stories.js, stories/XAxisPlacements.stories.js
For completeness, support `TOP`/`BOTTOM`/`BOTH` configurations for the
x-axis placement.
=> Support top/bottom/both x-axis configurations

src/components/DataProvider/index.js
I don't know what I was thinking when I wrote this.
=> Rewrite undefinedTruthiness

src/components/DataProvider/index.js
This was a bad merge resolution with 545e1cd621e4
=> Fix a merge conflict

src/components/GridLines/index.js
This regression was due to missing this in 36361e40
=> Have GridLines track ySubDomain rather than yDomain

package.json
=> Introduce 0.4

src/components/AxisCollection/YAxis.js, src/utils/proptypes.js, stories/SeriesCollections.stories.js
Collections don't NEED a color -- they can just fall back to a default.
=> Don't make color a requirement for collections

.cognite-git.json
This will provide a reference for the current base branch as well as who
will review PRs.
=> Add .cognite-git.json config file

src/components/DataProvider/index.js
`onTimeSubDomainChanged` should be called after the `timeSubDomain` has actually been updated
=> call onTimeSubDomainChanged in setState callback

src/components/DataProvider/index.js
allows calling application to be aware of the last data points for each series
=> call onFetchData with last points per series

src/components/DataProvider/index.js, src/components/InteractionLayer/index.js
- set ruler in `componentDidMount` and when width changes since we are now using the HOC with size-me
- compare `timeSubDomain` in `componentWillReceiveProps` instead of `subDomainsByItemId` since there is something broken with the update of `subDomainsByItemId`
=>  set ruler in componentDidMount and when width changes

src/components/Scatterplot/index.js
The scatterplot no longer has a single shared Y axis, so it needs to
handle the number of displayed axes correctly.
=> Correctly compute the width of the scatterplot

src/components/DataProvider/index.js
- also recalculate domains when the series data becomes non-empty
=> Handle empty series data when calculating domains from data

stories/InteractionLayer.stories.js, stories/Scatterplot.stories.js, stories/loaders.js
Prove the behavior that the ruler labels never overlap by adding a story
to demonstrate (and test) this fact.
=> Add a story showing that the labels don't overlap

.cognite-git.json
Since her internship is over ( :-( ), she probably doesn't want to get every PR.
@jasmineleeson if you disagree, speak up (or revert this!)
=> Remove jasmineleeson from default reviewer list

.cognite-git.json
Alex changed his username recently; update the `.cognite-git.json` file
accordingly.
=> Update Alex's username

src/components/ContextChart/index.js
ContextChart does not hold any state. As such, it should not be a
stateful ES6 class. Instead, convert it to a stateless function
(supported by helper functions).
=> Convert ContextChart to a stateless function

src/components/InteractionLayer/index.js
This should have been removed in 6c755dc.
=> Remove an obsolete FIXME

src/components/AxisCollection/YAxis.js, src/components/AxisCollection/index.js, stories/AxisCollection.stories.js
AxisCollection does not have any state, so it should not be an ES6
class. This change also introduces separate stories for testing the
AxisCollection component in isolation.
Additionally, this plumbs through the ticks prop so that the number of
ticks is externally-controllable by the calling application.
=> Make AxisCollection a stateless function

src/components/InteractionLayer/index.js, src/components/LineChart/index.js
LineChart doesn't hold any state, so convert it into a stateless
component instead of an ES6 class.
=> Convert LineChart to a stateless component

src/components/XAxis/index.js
The XAxis component does not maintain any state -- convert it to be a
stateless function.
=> Convert XAxis to a stateless function

src/components/AxisCollection/YAxis.js
The YAxis component does not contain state -- convert it to a stateless
component.
=> Convert YAxis to a stateless component

package.json
0.5.0-rc.x is now open for breaking API changes.
=> Open 0.5.0-rc.0 for business

src/components/DataProvider/index.js, src/components/Scaler/index.js, stories/LineChart.stories.js
Expose onUpdateDomains callback from DataProvider
This callback will be triggered every time any of the domains for any of collections or series has been changed
=> Expose onUpdateDomains callback from DataProvider

src/components/DataProvider/index.js, src/components/Scaler/index.js, stories/LineChart.stories.js
This callback will be triggered every time any of the domains for any of collections or series has been changed
=> Expose onUpdateDomains callback from DataProvider (#256)

Jenkinsfile
Instead of maintaining a hardcoded list, use a slightly better 0.* match.
=> Build all 0.* branches

src/components/LineChart/index.js, stories/LineChart.stories.js
Relates to https://github.com/cognitedata/operational-intelligence/issues/2119
=> Allow specifying custom # of y-axis ticks when using LineChart (#255)

src/components/AxisCollection/CollapsedAxis.js
This component has no state; there's no reason it should be an ES6
class. Instead, convert it to be a functional component.
=> Convert CollapsedAxis to a functional component

Jenkinsfile
=> Use the correct local variable

.cognite-git.json, CODEOWNERS
=> Add Kirien to owners and reviewers

src/components/Scaler/index.js
* Fix https://github.com/cognitedata/griff-react/issues/262
* The closing brace for one of the conditions was in the wrong place
=> Fix timeSubDomain DataProvider prop update not taking effect

scripts/publish-release.sh
It would be useful to see what was included in the newest version.
=> Add last commit to the Slack message

src/components/GridLines/index.tsx, src/components/Scaler/index.tsx, src/internal.d.ts
Bring some self-documenting props to GridLines by porting this component
to TypeScript.
=> Port GridLines to TypeScript

src/components/Area/index.tsx
Bring TypeScript to another small component: Area
=> Port Area to TypeScript

src/components/Brush/index.tsx
Bring type safety to the Brush component.
=> Port Brush to TypeScript

src/components/XAxis/index.tsx, src/react-sizeme.d.ts
Bring self-documenting types to XAxis
=> Port XAxis to TypeScript

src/components/Line/index.tsx, src/components/LineCollection/index.tsx, src/components/Points/index.tsx, src/internal.d.ts
Now that Line has been ported, follow through with LineCollection.
=> Port LineCollection to TypeScript

src/components/LineChart/index.js
=> Ensure line chart height and width are positive

src/components/ContextChart/index.js, src/components/InteractionLayer/index.js, src/components/Scaler/index.tsx, stories/LineChart.stories.js
Allow charts to exist which don't have any Series. This can happen if
Griff is used in an application where the user can dynamically build a
chart, for example.
=> Support having no Series

Jenkinsfile, package.json, yarn.lock
Report the stages to GitHub as separate contexts, and make sure to run
through all of the contexts.
=> Build each PR

.storybook/addons.ts, package.json, src/components/Scatterplot/index.js, stories/Scatterplot.stories.js, yarn.lock
Take width of y-axis and height of x-axis in props of scatter plot to set custom value. This is similar to existing functionality on line charts.
=> Custom scatter plot axes sizes

.storybook/config.tsx, rollup.config.js
Set it up to allow stories to be colocatd with the components but also
excluded from the build.
=> Exclude helper files (stories, tests) from the build

src/components/Area/index.tsx, src/components/AxisCollection/YAxis.js, src/components/InteractionLayer/index.js
Add an id specific classname to each y-axis and area to allow them to be
queried.
Fixes: [OI-1988]
[OI-1988]: https://cognitedata.atlassian.net/browse/OI-1988
=> [OI-1988] Add classnames with ids

src/components/LineChart/Layout.js, src/components/LineChart/__snapshots__/LineChart.spec.tsx.snap, stories/GridLines.stories.js, stories/SeriesCollections.stories.js, stories/XAxisPlacements.stories.js, stories/YAxisPlacements.stories.js
Based on scatterplot implementation
Related to [OI-2219]
[OI-2219]: https://cognitedata.atlassian.net/browse/OI-2219
=> [OI-2219] Add grid template row and column values
